name: E2E on Chrome

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Cypress run
        env:
          REPOSITORIES_GITHUB_AUTH: ${{secrets.REPOSITORIES_GITHUB_AUTH}}
          TWITTER_BEARER_TOKEN: ${{secrets.TWITTER_BEARER_TOKEN}}
        uses: cypress-io/github-action@v5.0.7
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
